# action.yml
name: 'Analyse your HTTP response headers'
description: 'Quickly and easily assess the security of your HTTP response headers'
inputs:
  url:
    description: 'URL to analyse'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
